"""
Markdown report generator for CRAPQuants.

Produces Markdown output for PR comments, documentation, and wikis.
"""

from __future__ import annotations

from crapquants.core.merge import MergedFileResult
from crapquants.frameworks.tags import DiagnosticTag, Severity


def generate_markdown_report(
    results: list[MergedFileResult],
    all_tags: dict[str, list[DiagnosticTag]],
    phs_score: float | None = None,
    analysis_level: str = "standard",
    top_n: int = 20,
    show_passing: bool = False,
) -> str:
    """
    Generate a Markdown report.

    Args:
        results: List of merged file results.
        all_tags: Dict mapping "file:func" to diagnostic tags.
        phs_score: Pragmatic Health Score.
        analysis_level: Analysis level used.
        top_n: Max functions to include.
        show_passing: Include passing functions.

    Returns:
        Markdown string.
    """
    lines: list[str] = []

    total_functions = sum(len(r.functions) for r in results)
    crappy_count = sum(
        1 for r in results for f in r.functions if f.crap.is_crappy
    )
    all_crap = [f.crap.crap_score for r in results for f in r.functions]
    avg_crap = sum(all_crap) / max(len(all_crap), 1)
    max_crap = max(all_crap, default=0.0)

    # Header
    lines.append("# CRAPQuants Report")
    lines.append("")
    lines.append(f"**Analysis Level:** {analysis_level}")
    lines.append(f"**Files:** {len(results)} | **Functions:** {total_functions}")
    lines.append(f"**CRAPpy Functions:** {crappy_count} / {total_functions}")
    lines.append(f"**Average CRAP:** {avg_crap:.1f} | **Max CRAP:** {max_crap:.1f}")
    if phs_score is not None:
        emoji = _phs_emoji(phs_score)
        lines.append(f"**Codebase Health (PHS):** {phs_score:.0f}/100 {emoji}")
    lines.append("")

    # Gate result
    if crappy_count > 0:
        lines.append(f"> **CI Gate: FAIL** — {crappy_count} function(s) exceed CRAP threshold of 30.")
    else:
        lines.append("> **CI Gate: PASS** — All functions below CRAP threshold.")
    lines.append("")

    # Function table
    functions = []
    for r in results:
        for f in r.functions:
            functions.append((f, r.file_path))
    functions.sort(key=lambda x: x[0].crap.crap_score, reverse=True)

    if not show_passing:
        functions = [(f, p) for f, p in functions if f.crap.is_crappy]

    if functions:
        functions = functions[:top_n]
        lines.append("## Hotspots")
        lines.append("")
        lines.append("| Function | File | CRAP | CC | CogC | Cov% | Tags |")
        lines.append("|----------|------|------|----|------|------|------|")

        for func, file_path in functions:
            m = func.metrics
            c = func.crap
            tag_key = f"{file_path}:{m.name}"
            func_tags = all_tags.get(tag_key, [])
            tag_str = ", ".join(
                f"`[{t.framework.value}] {t.tag_id}`"
                for t in func_tags[:3]
            ) or "—"
            crap_badge = f"**{c.crap_score:.1f}**" if c.is_crappy else f"{c.crap_score:.1f}"
            short_path = _shorten_path(file_path)
            lines.append(
                f"| `{m.name}` | `{short_path}` | {crap_badge} | {m.cyclomatic_complexity} "
                f"| {m.cognitive_complexity} | {c.coverage:.0f}% | {tag_str} |"
            )
        lines.append("")

    # Recommendations
    recs_list = []
    for key, tags in all_tags.items():
        for tag in tags:
            if tag.recommendations and tag.severity in (Severity.CRITICAL, Severity.HIGH):
                func_name = key.split(":")[-1] if ":" in key else key
                recs_list.append((func_name, tag))

    if recs_list:
        lines.append("## Top Recommendations")
        lines.append("")
        for i, (func_name, tag) in enumerate(recs_list[:10], 1):
            rec = tag.recommendations[0]
            severity_icon = {"critical": "🔴", "high": "🟠", "warning": "🟡", "info": "🔵"}.get(
                tag.severity.value, "⚪"
            )
            lines.append(
                f"{i}. {severity_icon} **{func_name}** — {rec.action} "
                f"*({tag.tag_id}, {rec.rationale})*"
            )
        lines.append("")

    # Glossary — makes report self-documenting for first-time readers
    from crapquants.reporting.glossary import build_glossary_markdown
    lines.append(build_glossary_markdown())

    # Footer
    lines.append("---")
    lines.append("*Generated by [CRAPQuants](https://github.com/dockyardtechlabs/crapquants) — Dockyard Techlabs*")

    return "\n".join(lines)


def write_markdown_report(
    results: list[MergedFileResult],
    all_tags: dict[str, list[DiagnosticTag]],
    output_path: str,
    phs_score: float | None = None,
    analysis_level: str = "standard",
    top_n: int = 20,
) -> str:
    """Generate and write Markdown report to file."""
    md = generate_markdown_report(results, all_tags, phs_score, analysis_level, top_n)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md)
    return output_path


def _phs_emoji(score: float) -> str:
    if score >= 80:
        return "🟢"
    if score >= 60:
        return "🟡"
    if score >= 40:
        return "🟠"
    return "🔴"


def _shorten_path(path: str, max_len: int = 30) -> str:
    if len(path) <= max_len:
        return path
    parts = path.split("/")
    if len(parts) <= 2:
        return f"...{path[-(max_len - 3):]}"
    return f".../{'/'.join(parts[-2:])}"
